@id=9252a62e-5fe1-4ee7-bd60-77c97a4a6ae4

PUT http://localhost:5115/patientrecords/{{id}}
Content-Type: application/json

{
    "firstName": "Peter 2",
    "lastName": "Chan",
    "dateOfBirth": "1980-05-15",
    "gender": "Male",
    "contactInformation": 
    {
      "email": "peterchan@gmail.com",
      "phone": "111-1111-1111",
      "address": 
      {
      "street": "123 Main St",
      "city": "Anytown",
      "state": "CA",
      "postalCode": "A1A1A1"
      }
    },
    "medicalHistory":
    [
        {
        "Allergies": "Penicillin",
        "Conditions": "Hypertension",
        "Medications": "Aspirin"
        }
    ]
}

